const fs = require("fs");
const { exec } = require("child_process");
const express = require("express");
const path = require("path");
const app = express();

app.use(express.json());

// --- FIX: Correctly point to the project root folder ---
// Since this file is in /server/, we need to go up one level ('..') to find /pages/
const projectRoot = path.join(__dirname, '..');

// 1. Serve static files from the project root (where index.html and pages/ live)
app.use(express.static(projectRoot));

// 2. Explicitly handle the homepage route
app.get('/', (req, res) => {
    // Try to send index.html from the root
    res.sendFile(path.join(projectRoot, 'index.html'));
});

// --- API Configuration ---
const FIRMWARE_DIR = "/var/www/ar3s/firmware/avr/";
const SKETCH_DIR = "/tmp/test-sketch/";
const SKETCH_FILE = "sketch.ino";

// --- API ENDPOINTS ---

app.post("/api/copilot", (req, res) => {
  const { prompt, mode, existingCode } = req.body;
  
  if (!prompt && mode !== 'debug') {
      return res.status(400).json({ error: "Prompt is required" });
  }

  setTimeout(() => {
    let generatedCode = "";
    if (mode === "pinout") {
      generatedCode = `/* Athena AI Pinout for: ${prompt} */\n// (Pinout details would go here)`;
    } else if (mode === "debug") {
      generatedCode = `// Athena AI Debug:\n// Checking code...\n${existingCode || ""}\n// No errors found.`;
    } else {
      generatedCode = `// Generated by Athena AI\n// Prompt: ${prompt}\n\nvoid setup() {\n  Serial.begin(115200);\n}\n\nvoid loop() {\n}`;
    }
    res.json({ success: true, code: generatedCode, mode: mode || "generate" });
  }, 1000);
});

app.post("/api/build/avr", (req, res) => {
  const { fqbn, files } = req.body; 
  
  const buildDir = path.join(projectRoot, "build_tmp");
  
  if (fs.existsSync(buildDir)) fs.rmSync(buildDir, { recursive: true, force: true });
  fs.mkdirSync(buildDir, { recursive: true });

  if (files && Array.isArray(files)) {
      files.forEach(file => {
          // Safety: Prevent hacking by removing ".." from filenames
          const safeName = path.basename(file.name); 
          fs.writeFileSync(path.join(buildDir, safeName), file.content);
      });
  
  } else {
      const code = req.body.code || req.body.sketch;
      fs.writeFileSync(path.join(buildDir, "sketch.ino"), code);
  }

  const board = fqbn || "arduino:avr:nano:cpu=atmega328old";
  const cmd = `docker run --rm -v "${buildDir}:/src" arduino-cli-avr compile --fqbn ${board} --output-dir /src /src`;

  exec(cmd, (error, stdout, stderr) => {
    if (error) {
        return res.status(500).json({ success: false, error: stderr || stdout });
    }

    const hexFiles = fs.readdirSync(buildDir).filter(f => f.endsWith(".hex"));
    
    if (hexFiles.length > 0) {
        const hexSource = path.join(buildDir, hexFiles[0]);
        const hexDest = path.join(projectRoot, "firmware.hex");
        fs.renameSync(hexSource, hexDest); // Move to public folder
        
        res.json({ success: true, hexUrl: "/firmware.hex", log: stdout });
    } else {
         res.status(500).json({ success: false, error: "Build success, but HEX file missing." });
    }
  });
});

const port = process.env.PORT || 8081;
app.listen(port, () => {
  console.log(`Ar3s AVR API listening on port ${port}`);
  console.log(`Serving files from: ${projectRoot}`);
});
