const fs = require("fs");
const { exec } = require("child_process");
const express = require("express");
const path = require("path");
const app = express();
app.use(express.json());

// Serve static files from the parent directory
app.use(express.static(path.join(__dirname, '..')));

const FIRMWARE_DIR = "/var/www/ar3s/firmware/avr/";
const SKETCH_DIR = "/tmp/test-sketch/";
const SKETCH_FILE = "sketch.ino";

app.post("/api/build/avr", (req, res) => {
  const { code, fqbn } = req.body;

  if (!fs.existsSync(SKETCH_DIR)) fs.mkdirSync(SKETCH_DIR, { recursive: true });
  if (!fs.existsSync(FIRMWARE_DIR)) fs.mkdirSync(FIRMWARE_DIR, { recursive: true });

  const sketchFilePath = `${SKETCH_DIR}${SKETCH_FILE}`;
  fs.writeFileSync(sketchFilePath, code);

  const buildCommand = `docker run --rm \
    -v ${SKETCH_DIR}:/work/sketch \
    -v ${FIRMWARE_DIR}:/work/build \
    arduino-cli-avr \
    compile --fqbn ${fqbn} --output-dir /work/build --warnings all /work/sketch/sketch.ino`;

  exec(buildCommand, (err, stdout, stderr) => {
    if (err) {
      console.error("Build failed:", stderr);
      return res.status(500).json({ error: "Compilation failed", details: stderr });
    }

    const hexFiles = fs.readdirSync(FIRMWARE_DIR)
      .filter((file) => file.endsWith(".hex"))
      .map((fileName) => ({
        fileName,
        fullPath: `${FIRMWARE_DIR}${fileName}`,
        updateTime: fs.statSync(`${FIRMWARE_DIR}${fileName}`).mtimeMs
      }))
      .sort((a, b) => b.updateTime - a.updateTime); // Sort by modified time desc

    const latestHex = hexFiles.length > 0 ? hexFiles[0].fileName : null;
    if (!latestHex) {
      return res.status(500).json({ error: "No HEX file produced" });
    }

    return res.json({
      artifactUrl: `/firmware/avr/${latestHex}`,
      log: stdout
    });
  });
});

// AI Copilot endpoint - simulates code generation with wiring diagrams
app.post("/api/copilot", (req, res) => {
  const { userPrompt, prompt, mode, existingCode } = req.body;
  
  // Accept both 'userPrompt' (new API) and 'prompt' (backward compatibility)
  const finalPrompt = userPrompt || prompt;
  
  if (!finalPrompt) {
    return res.status(400).json({ error: "userPrompt is required" });
  }

  // Simulate AI processing delay
  setTimeout(() => {
    let firmware_code = "";
    let wiring_diagram = [];
    
    if (mode === "pinout" || mode === "diagram") {
      // Generate pinout diagram with wiring information
      firmware_code = `/*
 * PINOUT DIAGRAM
 * Generated by Athena AI
 * Prompt: ${finalPrompt}
 * 
 * Arduino Uno/Nano Pin Configuration:
 * 
 * Digital Pins:
 * D0  (RX)  - Serial Receive
 * D1  (TX)  - Serial Transmit
 * D2-D13    - General Purpose I/O
 * D13       - Built-in LED
 * 
 * Analog Pins:
 * A0-A5     - Analog Input (can be used as digital I/O)
 * 
 * Power:
 * VIN       - Input Voltage (7-12V)
 * 5V        - 5V Output
 * 3.3V      - 3.3V Output
 * GND       - Ground
 * 
 * PWM Pins: ~D3, ~D5, ~D6, ~D9, ~D10, ~D11
 */

// Example pin configuration
const int LED_PIN = 13;
const int BUTTON_PIN = 2;
const int SENSOR_PIN = A0;

void setup() {
  pinMode(LED_PIN, OUTPUT);
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(SENSOR_PIN, INPUT);
}

void loop() {
  int sensorValue = analogRead(SENSOR_PIN);
  if (digitalRead(BUTTON_PIN) == LOW) {
    digitalWrite(LED_PIN, HIGH);
  } else {
    digitalWrite(LED_PIN, LOW);
  }
}`;

      // Generate wiring diagram data
      wiring_diagram = [
        {
          source: "Arduino Pin 13",
          target: "LED (Anode)",
          label: "Digital Output",
          color: "#00d9ff"
        },
        {
          source: "LED (Cathode)",
          target: "GND",
          label: "Ground",
          color: "#8b949e",
          intermediate_component: {
            type: "resistor",
            value: "220Ω",
            position: "between"
          }
        },
        {
          source: "Arduino Pin 2",
          target: "Button (Pin 1)",
          label: "Digital Input",
          color: "#7c4dff"
        },
        {
          source: "Button (Pin 2)",
          target: "GND",
          label: "Ground",
          color: "#8b949e"
        },
        {
          source: "Arduino A0",
          target: "Sensor (OUT)",
          label: "Analog Input",
          color: "#ff006e"
        },
        {
          source: "Sensor (VCC)",
          target: "5V",
          label: "Power",
          color: "#00ff88"
        },
        {
          source: "Sensor (GND)",
          target: "GND",
          label: "Ground",
          color: "#8b949e"
        }
      ];
    } else if (mode === "debug") {
      // Debug mode - add debugging statements to existing code
      firmware_code = `// Athena AI Debug Suggestions:
// 1. Add Serial.begin(115200) in setup()
// 2. Add Serial.print() statements to track variable values
// 3. Check for common issues:

${existingCode || ""}

/*
 * DEBUG TIPS:
 * - Use Serial Monitor (115200 baud)
 * - Check pin connections
 * - Verify power supply voltage
 * - Look for timing issues in delays
 */`;

      // Simple wiring for debugging context
      wiring_diagram = [
        {
          source: "Arduino TX (Pin 1)",
          target: "USB Serial",
          label: "Debug Output",
          color: "#00d9ff"
        }
      ];
    } else {
      // Generate mode - create new code based on prompt
      firmware_code = `#include <Arduino.h>

// Generated by Athena AI
// Prompt: ${finalPrompt}

// Pin definitions
const int LED_PIN_1 = 12;
const int LED_PIN_2 = 13;

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN_1, OUTPUT);
  pinMode(LED_PIN_2, OUTPUT);
  
  Serial.println("============================");
  Serial.println("Athena AI - System Online");
  Serial.println("============================");
  Serial.println("Prompt: ${finalPrompt}");
  Serial.println("Firmware initialized successfully");
}

void loop() {
  // Blink pattern for two LEDs
  digitalWrite(LED_PIN_1, HIGH);
  digitalWrite(LED_PIN_2, LOW);
  delay(500);
  
  digitalWrite(LED_PIN_1, LOW);
  digitalWrite(LED_PIN_2, HIGH);
  delay(500);
  
  Serial.println("System running...");
}`;

      // Generate wiring diagram for the code
      wiring_diagram = [
        {
          source: "Arduino Pin 12",
          target: "LED 1 (Anode)",
          label: "Digital Output",
          color: "#00d9ff"
        },
        {
          source: "LED 1 (Cathode)",
          target: "GND",
          label: "Ground",
          color: "#8b949e",
          intermediate_component: {
            type: "resistor",
            value: "220Ω",
            position: "between"
          }
        },
        {
          source: "Arduino Pin 13",
          target: "LED 2 (Anode)",
          label: "Digital Output",
          color: "#7c4dff"
        },
        {
          source: "LED 2 (Cathode)",
          target: "GND",
          label: "Ground",
          color: "#8b949e",
          intermediate_component: {
            type: "resistor",
            value: "220Ω",
            position: "between"
          }
        }
      ];
    }

    res.json({
      success: true,
      firmware_code: firmware_code,
      wiring_diagram: wiring_diagram,
      mode: mode || "generate"
    });
  }, 1500); // Simulate AI processing time
});

// Start server
const port = process.env.PORT || 8081;
app.listen(port, () => {
  console.log(`Ar3s AVR build API listening on port ${port}`);
});
