const fs = require("fs");
const { exec } = require("child_process");
const express = require("express");
const path = require("path");
const app = express();
app.use(express.json());

// Serve static files from specific directories only
app.use('/assets', express.static(path.join(__dirname, '..', 'assets')));
app.use('/pages', express.static(path.join(__dirname, '..', 'pages')));
app.use('/firmware', express.static(path.join(__dirname, '..', 'firmware')));

// Serve root HTML files
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'index.html'));
});
app.get('/index.html', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'index.html'));
});

const FIRMWARE_DIR = "/var/www/ar3s/firmware/avr/";
const SKETCH_DIR = "/tmp/test-sketch/";
const SKETCH_FILE = "sketch.ino";

app.post("/api/copilot", (req, res) => {
  const { prompt, mode, code } = req.body;

  // Simulate AI response for now
  // In production, this would call an actual AI service like OpenAI, Claude, etc.
  
  if (!prompt || !mode) {
    return res.status(400).json({ error: "Missing required fields: prompt and mode" });
  }

  // Simulate processing delay
  setTimeout(() => {
    let generatedCode = "";
    
    if (mode === "generate") {
      // Generate new code based on prompt
      generatedCode = `// Generated by Athena AI based on: ${prompt}\n#include <Arduino.h>\n\nvoid setup() {\n  // Setup code here\n  Serial.begin(115200);\n  pinMode(LED_BUILTIN, OUTPUT);\n}\n\nvoid loop() {\n  // Loop code here\n  digitalWrite(LED_BUILTIN, HIGH);\n  delay(1000);\n  digitalWrite(LED_BUILTIN, LOW);\n  delay(1000);\n}`;
    } else if (mode === "debug") {
      // Debug existing code
      generatedCode = `// Athena AI Debug Analysis for: ${prompt}\n// Original code:\n${code || "// No code provided"}\n\n// Suggested improvements:\n// 1. Check for proper initialization\n// 2. Verify pin configurations\n// 3. Add error handling`;
    } else if (mode === "pinout") {
      // Generate pinout diagram information
      generatedCode = `// Athena AI Pinout Diagram\n// Board: Arduino Uno\n// Generated for: ${prompt}\n\n/*\nPinout Configuration:\n- Pin 13: LED_BUILTIN\n- Pin 2-12: Digital I/O\n- Pin A0-A5: Analog Input\n- Pin 0-1: Serial (TX/RX)\n\nConnections:\n- LED: Pin 13\n- Serial: Pins 0-1 (USB)\n*/\n\n// Pin definitions\n#define LED_PIN 13\n#define BUTTON_PIN 2\n#define SENSOR_PIN A0`;
    } else {
      return res.status(400).json({ error: "Invalid mode. Use 'generate', 'debug', or 'pinout'" });
    }

    res.json({
      code: generatedCode,
      success: true,
      message: "Code generated successfully by Athena AI"
    });
  }, 1000); // Simulate 1 second processing time
});

app.post("/api/build/avr", (req, res) => {
  const { code, fqbn } = req.body;

  if (!fs.existsSync(SKETCH_DIR)) fs.mkdirSync(SKETCH_DIR, { recursive: true });
  if (!fs.existsSync(FIRMWARE_DIR)) fs.mkdirSync(FIRMWARE_DIR, { recursive: true });

  const sketchFilePath = `${SKETCH_DIR}${SKETCH_FILE}`;
  fs.writeFileSync(sketchFilePath, code);

  const buildCommand = `docker run --rm \
    -v ${SKETCH_DIR}:/work/sketch \
    -v ${FIRMWARE_DIR}:/work/build \
    arduino-cli-avr \
    compile --fqbn ${fqbn} --output-dir /work/build --warnings all /work/sketch/sketch.ino`;

  exec(buildCommand, (err, stdout, stderr) => {
    if (err) {
      console.error("Build failed:", stderr);
      return res.status(500).json({ error: "Compilation failed", details: stderr });
    }

    const hexFiles = fs.readdirSync(FIRMWARE_DIR)
      .filter((file) => file.endsWith(".hex"))
      .map((fileName) => ({
        fileName,
        fullPath: `${FIRMWARE_DIR}${fileName}`,
        updateTime: fs.statSync(`${FIRMWARE_DIR}${fileName}`).mtimeMs
      }))
      .sort((a, b) => b.updateTime - a.updateTime); // Sort by modified time desc

    const latestHex = hexFiles.length > 0 ? hexFiles[0].fileName : null;
    if (!latestHex) {
      return res.status(500).json({ error: "No HEX file produced" });
    }

    return res.json({
      artifactUrl: `/firmware/avr/${latestHex}`,
      log: stdout
    });
  });
});

// Start server
const port = process.env.PORT || 8081;
app.listen(port, () => {
  console.log(`Ar3s AVR build API listening on port ${port}`);
});
